export const data = [{
        dataSort: 'beaf',
        img: 'pizza-01@2x.png',
        name: "Итальянская",
        description: "Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик",
        price: '699',
        id: 1,
    },
    {
        dataSort: 'cheese',
        img: 'pizza-02.png',
        name: "Маргарита",
        description: "Тесто со шпинатом, молодой сыр и колбаски, много колбасок",
        price: '479',
        id: 2
    },
    {
        dataSort: 'cheese',
        img: 'pizza-03.png',
        name: "Барбекю",
        description: "Циплёнок (маленький кура), оливки, моцарелла, соус барбекю",
        price: '699',
        id: 3,
    },
    {
        dataSort: 'cheese',
        img: 'pizza-04.png',
        name: "Вегетарианская",
        description: "Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик",
        price: '399',
        id: 4,
    },
    {
        dataSort: 'cheese',
        img: 'pizza-05.png',
        name: "Мясная",
        description: "Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик",
        price: '699',
        id: 5,
    },
    {
        dataSort: 'vegetable',
        img: 'pizza-06.png',
        name: "Овощная",
        description: "Тесто со шпинатом, молодой сыр и колбаски, много колбасок",
        price: '479',
        id: 6,
    },
    {
        dataSort: 'vegetable',
        img: 'pizza-07.png',
        name: "Римская",
        description: "Циплёнок (маленький кура), оливки, моцарелла, соус барбекю",
        price: '699',
        id: 7,
    },
    {
        dataSort: 'vegetable',
        img: 'pizza-08.png',
        name: "С грибами",
        description: "Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик",
        price: '399',
        id: 8,
    },
    {
        dataSort: 'hot',
        img: 'pizza-09.png',
        name: "Сырная",
        description: "Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик",
        price: '699',
        id: 9,
    },
    {
        dataSort: 'hot',
        img: 'pizza-10.png',
        name: "Четыре сыра",
        description: "Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик",
        price: '699',
        id: 10,
    },
    {
        dataSort: 'hot',
        img: 'pizza-11.png',
        name: "Пепперони Фреш с томатами",
        description: "Циплёнок (маленький кура), оливки, моцарелла, соус барбекю",
        price: '699',
        id: 11,
    },
    {
        dataSort: 'hot',
        img: 'pizza-12.png',
        name: "Ветчина и сыр",
        description: "Томат, шампиньон, сыр, оливки, чили, соус, тесто, базилик",
        price: '699',
        id: 12,
    },
]